### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by mueslo** [tvdsluijs/sh-python-installer#1]
You should consider actually creating a debian package, so whatever is installed can be easily uninstalled.

See also: https://wiki.debian.org/HowToPackageForDebian#Building_Debian_packages

**Comment by tvdsluijs** [comment]
Hi @mueslo that is actually a good idea. I do however should build one for Ubuntu also I'm guessing.

Thank you for your idea!

**Comment by tvdsluijs** [comment]
I'll let you know when I created it!
