### ISSUE TITLE
Your comment on docker is valid but misses some usecases

### ISSUE THREAD

**Issue by Duckle29** [tvdsluijs/sh-python-installer#17]
Hi there.

Thanks for this script, so far it's chugging along and seems to be doing good :)

While I generally agree with your push towards containers, that doesn't cover the usecase of simple RPi based HMIs.
When you're using python and an RPi with a touch display to make a simple GUI, as far as I'm aware you're not going to be able to run that through a docker image. 

For this use-case it's still useful to have a newer version of python.
You also don't have to set it as the system default, as you should of course always be working with virtual environments of some sort. Having the newer version is relevant to be able to have venvs with newer versions

**Comment by tvdsluijs** [comment]
Hi @Duckle29 wel, for me the docker container is just to test the python installer script. It is really usefull to just destroy the docker instance and test is all again.
