### ISSUE TITLE
Installed version not known

### ISSUE THREAD

**Issue by RadioMCMLVI** [tvdsluijs/sh-python-installer#2]
Hello,
I used your bash script to install Python 3.8.12 on my RPI4-8GB Ram with Raspbian Buster where python 3.7.3 is installed.

Script worked fine but when typing **python --version** the result is always **Python 3.7.3**

The workaround I used was to add the following lines to user's .bash_aliases file:
alias python = /usr/bin /python3.8
alias python3 = /usr/bin/python3.8

Therefore, after logout-login or reboot the command **python --version** and **python3 --version** give the result of **Python 3.8.12.**

Regards

**Comment by tvdsluijs** [comment]
Hi @RadioMCMLVI thank you for your message.

Strange that you add those two lines to your .bash_aliases file. Did you already had lines in it to your installed 3.7.3 version?

**Comment by RadioMCMLVI** [comment]
Hi,

For Python 3.7.3 version I didn't had these lines in my .bash_aliases
file because it's the default version in Raspbian Buster.

In fact, I am using eric6 IDE for my python developments. Despite these
two lines, he still sees python 3.7.3

I would tend to say that eric6 works in 'su' mode hence the 3.7.3
version it sees. These lines in .bash_aliases only define the version of
python for user 'pi'.


Le 08/12/2021 à 08:31, Theo van der Sluijs a écrit :

**Comment by tvdsluijs** [comment]
I think both pi as su users have their own .bash_aliases file.
