### ISSUE TITLE
Script uses bash but declares sh

### ISSUE THREAD

**Issue by hlascelles** [tvdsluijs/sh-python-installer#20]
If you run this script, say, in docker, it uses `sh`: https://github.com/tvdsluijs/sh-python-installer/blob/34905d6d66bcab9405d6292685256cf6397fbe5f/python.sh#L1

But that fails as the script requires bash:

```
43: python.sh: [[: not found
```

Should the shebang be changed:

```bash
# From:
#!/usr/bin/env sh

# To:
#!/usr/bin/env bash
```

**Comment by tvdsluijs** [comment]
Consider it done

**Comment by hlascelles** [comment]
:bow:
