### ISSUE TITLE
Didnt work on pi

### ISSUE THREAD

**Issue by r35p3ct** [tvdsluijs/sh-python-installer#3]
`All Done!
Your new Python version should be 3.10.0
You can check this yourself by 'python --version'
It might be a good idea to update pip with : 'python pip install --upgrade pip'

Do not forget to give me a tip/donation for my hard :-) work!
https://itheo.tech/donate

Any questions?
Visit my site and contact me on my contact page https://itheo.tech/contact

Have Fun!
root@raspberrypi:/home/pi/py/neoline# python -V
Python 3.7.3
root@raspberrypi:/home/pi/py/neoline# python3 -V
Python 3.7.3`

**Comment by tvdsluijs** [comment]
Hi @r35p3ct can I help with anything?

**Comment by tvdsluijs** [comment]
Do you have python alias in your bash alias file?

**Comment by tvdsluijs** [comment]
Can you try to

alias Python3 >/dev/null 2>&1 && echo "Python3 is set as an alias" || echo "Python3 is not an alias"
or
alias Python >/dev/null 2>&1 && echo "Python is set as an alias" || echo "Python is not an alias"

**Comment by r35p3ct** [comment]
> alias Python3 >/dev/null 2>&1 && echo "Python3 is set as an alias" || echo "Python3 is not an alias"

```
root@raspberrypi:/home/pi/py/neoline# alias Python3 >/dev/null 2>&1 && echo "Python3 is set as an alias" || echo "Python3 is not an alias"
Python3 is not an alias
```

**Comment by r35p3ct** [comment]
I used this command to have version 3 by default. Maybe this is the problem ...
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10`

**Comment by tvdsluijs** [comment]
Ah, you have version 3 already installed.  Can you do a

update-alternatives --list python

and send me what you see

**Comment by r35p3ct** [comment]
hm...
`root@raspberrypi:/home/pi/py/neoline# update-alternatives --list python
/usr/bin/python3
/usr/bin/python3.10`
It turns out everything is fine, only you need to delete the version below ...
