### ISSUE TITLE
SSL doesn't work in pip after install

### ISSUE THREAD

**Issue by pvanallen** [tvdsluijs/sh-python-installer#4]
After using your script to install Python 3.10.2, pip consistently fails with the following error:

`Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping`

I have done many searches, tried many things, but cannot find a successful way to fix this.

**Comment by clintandrewhall** [comment]
They mention how to fix this issue here: https://medium.com/@isma3il/install-python-3-6-or-3-7-and-pip-on-raspberry-pi-85e657aadb1e

Thanks for posting this issue.  I was about to run this script.

**Comment by Fornball** [comment]
Hey, same issue, above fix didnt work. Any help?
